#!/usr/bin/env bash
#
# lib/egress.sh — per-profile egress allowlist enforcement (ARD-0011, ARD-0015).
#
# Mechanism: container-side iptables rules installed at boot by the
# install-egress entrypoint script (templates/_common/bin/install-egress).
# This module is the host side — it:
#   1. Tells compose.sh what to splice into the dev service (cap_add + mount).
#   2. Writes the resolved allowlist to a file that's bind-mounted into the
#      container at /etc/boring/egress.allow.
#   3. After --learn-mode shutdown, reads NFLOG-derived JSON-Lines from the
#      egress-logger sidecar's ulogd.json (ARD-0015) and emits a proposed
#      YAML diff. The dmesg-based v0.3 path is gone — ulogd2 in the sidecar
#      is cross-platform (works on Mac+Orbstack where dmesg-from-container
#      doesn't see iptables LOG entries).

# egress_enabled <profile-json>
# Returns 0 if .egress.allow is non-empty, 1 otherwise. Used by compose.sh to
# decide whether to splice in cap_add / bind-mounts.
egress_enabled() {
  local profile_json="$1"
  local count
  count="$(jq -r '(.egress.allow // []) | length' <<<"$profile_json")"
  [[ "$count" -gt 0 ]]
}

# egress_write_allowlist_file <profile-json> <devcontainer-dir>
# Writes the resolved allowlist (one host per line) to
# <devcontainer-dir>/boring-runtime/egress.allow. The file is bind-mounted RO
# into the container at /etc/boring/egress.allow.
egress_write_allowlist_file() {
  local profile_json="$1"
  local devcontainer_dir="$2"
  [[ -z "$profile_json" ]] && die "egress_write_allowlist_file: missing profile JSON"
  [[ -d "$devcontainer_dir" ]] || die "egress_write_allowlist_file: missing dir: $devcontainer_dir"

  local runtime_dir="$devcontainer_dir/boring-runtime"
  mkdir -p "$runtime_dir"
  # Write via temp+rename so re-runs work: the destination has mode 0444 after
  # the previous run, which would make a direct `>` redirect fail with EACCES.
  # `mv -f` operates on the parent directory's perms, not the file's, so it
  # replaces a read-only destination cleanly. Pattern matches atomicWriteFile
  # in tools/boring-proxy/atomic.go.
  local tmp="$runtime_dir/egress.allow.tmp"
  {
    echo "# Generated by boring — do not edit. Source: .boring/profile.yaml :egress.allow"
    jq -r '(.egress.allow // [])[]' <<<"$profile_json"
  } > "$tmp"
  chmod 0444 "$tmp"
  mv -f "$tmp" "$runtime_dir/egress.allow"
}

# egress_propose_allowlist_diff <profile-json> <ulogd-json-path>
# ARD-0015. Reads the egress-logger sidecar's JSON-Lines output file (one
# JSON object per packet) — typically
# <repo>/.devcontainer/boring-runtime/egress-log/ulogd.json — extracts
# (dest.ip, dest.port) tuples, filters to entries whose oob.prefix matches
# "boring-egress-attempt" (ignoring anything else that might also be on
# NFLOG group 5), best-effort reverse-DNSes the IPs into hostnames, dedupes
# by (host, port), and emits a YAML diff snippet on stdout listing
# attempted-but-not-allowed hosts for the user to paste into
# .boring/profile.yaml.
#
# Usage: egress_propose_allowlist_diff "$profile_json" /path/to/ulogd.json
egress_propose_allowlist_diff() {
  local profile_json="$1"
  local log_source="$2"
  [[ -z "$profile_json" ]] && die "egress_propose_allowlist_diff: missing profile JSON"
  [[ -r "$log_source" ]] || { log_warn "egress: no log source at $log_source — nothing to propose"; return 0; }

  # Already-allowed hostnames (lowercased for comparison).
  local already
  already="$(jq -r '(.egress.allow // [])[] | ascii_downcase' <<<"$profile_json" | sort -u)"

  # ulogd2's JSON output is one JSON object per line. The plugin normalizes
  # field names by replacing the internal dot-separator with underscores, so
  # we read "dest_ip" / "dest_port" / "oob.prefix" — that last one is the one
  # exception (the prefix is stored under a key that does include a dot in
  # ulogd2's output). We filter on oob.prefix to skip unrelated NFLOG-group-5
  # traffic if anything else happens to share the group.
  #
  # `jq -c -R` reads raw lines, `fromjson?` swallows truncated/blank lines
  # (e.g. the last line if ulogd2 is mid-write when boring reads). select(...)
  # filters to our prefix entries; the final select drops rows with no
  # destination (control packets, IPv6, etc.).
  local tuples
  tuples="$(jq -c -R 'fromjson? // empty
                      | select((.["oob.prefix"] // "") | tostring | startswith("boring-egress-attempt"))
                      | select((.dest_ip // "") != "")
                      | "\(.dest_ip) \(.dest_port // "0")"
                     ' "$log_source" 2>/dev/null \
    | tr -d '"' \
    | sort -u)"

  if [[ -z "$tuples" ]]; then
    echo "# No egress attempts were logged in $log_source." >&2
    echo "# Either the session made no outbound requests, --learn-mode was not active," >&2
    echo "# or the egress-logger sidecar didn't start. Check 'docker compose logs egress-logger'." >&2
    return 0
  fi

  # Reverse-resolve each IP. Best-effort with a short timeout: a slow PTR
  # lookup shouldn't block diff generation. `getent hosts` is synchronous
  # with no built-in timeout, so we wrap with `timeout` when available
  # (coreutils on Linux, gtimeout via brew on Mac). On absence, fall back to
  # raw IPs to keep the diff useful.
  local timeout_cmd=""
  if command -v timeout >/dev/null 2>&1; then
    timeout_cmd="timeout 1"
  elif command -v gtimeout >/dev/null 2>&1; then
    timeout_cmd="gtimeout 1"
  fi

  local proposed=()
  local seen_hosts=""
  while IFS=' ' read -r ip port; do
    [[ -z "$ip" ]] && continue
    local host=""
    if [[ -n "$timeout_cmd" ]]; then
      host="$($timeout_cmd getent hosts "$ip" 2>/dev/null | awk '{print $2}' | head -1)"
    else
      host="$(getent hosts "$ip" 2>/dev/null | awk '{print $2}' | head -1)"
    fi
    [[ -z "$host" ]] && host="$ip"
    host="$(echo "$host" | tr '[:upper:]' '[:lower:]')"

    # Skip if already in allowlist.
    if grep -qxF "$host" <<<"$already"; then continue; fi
    # Dedupe across this run.
    if grep -qxF "$host" <<<"$seen_hosts"; then continue; fi
    seen_hosts+="$host"$'\n'
    proposed+=("$host  # port $port")
  done <<<"$tuples"

  if [[ "${#proposed[@]}" -eq 0 ]]; then
    echo "# All observed egress attempts were already in egress.allow. No diff to propose." >&2
    return 0
  fi

  echo "# Add to .boring/profile.yaml egress.allow:"
  echo "egress:"
  echo "  allow:"
  # Preserve existing entries first, then append.
  jq -r '(.egress.allow // [])[] | "    - " + .' <<<"$profile_json"
  for entry in "${proposed[@]}"; do
    echo "    - $entry"
  done
}
