#!/usr/bin/env bash
#
# lib/egress.sh — per-profile egress allowlist enforcement (ARD-0011).
#
# Mechanism: container-side iptables rules installed at boot by the
# install-egress entrypoint script (templates/_common/bin/install-egress).
# This module is the host side — it:
#   1. Tells compose.sh what to splice into the dev service (cap_add + mount).
#   2. Writes the resolved allowlist to a file that's bind-mounted into the
#      container at /etc/boring/egress.allow.
#   3. After --learn-mode shutdown, reads iptables LOG entries from the
#      container's kernel log and emits a proposed YAML diff.

# egress_enabled <profile-json>
# Returns 0 if .egress.allow is non-empty, 1 otherwise. Used by compose.sh to
# decide whether to splice in cap_add / bind-mounts.
egress_enabled() {
  local profile_json="$1"
  local count
  count="$(jq -r '(.egress.allow // []) | length' <<<"$profile_json")"
  [[ "$count" -gt 0 ]]
}

# egress_write_allowlist_file <profile-json> <devcontainer-dir>
# Writes the resolved allowlist (one host per line) to
# <devcontainer-dir>/boring-runtime/egress.allow. The file is bind-mounted RO
# into the container at /etc/boring/egress.allow.
egress_write_allowlist_file() {
  local profile_json="$1"
  local devcontainer_dir="$2"
  [[ -z "$profile_json" ]] && die "egress_write_allowlist_file: missing profile JSON"
  [[ -d "$devcontainer_dir" ]] || die "egress_write_allowlist_file: missing dir: $devcontainer_dir"

  local runtime_dir="$devcontainer_dir/boring-runtime"
  mkdir -p "$runtime_dir"
  {
    echo "# Generated by boring — do not edit. Source: .boring/profile.yaml :egress.allow"
    jq -r '(.egress.allow // [])[]' <<<"$profile_json"
  } > "$runtime_dir/egress.allow"
  chmod 0444 "$runtime_dir/egress.allow"
}

# egress_propose_allowlist_diff <profile-json> <log-source>
# Reads iptables LOG entries from <log-source> (typically the output of
# `devcontainer exec ... -- dmesg`), greps for the install-egress LOG prefix,
# extracts destination IPs, reverse-resolves them, dedupes (host,port), and
# emits a YAML diff snippet on stdout listing attempted-but-not-allowed hosts.
#
# Usage: egress_propose_allowlist_diff "$profile_json" /path/to/captured-dmesg
egress_propose_allowlist_diff() {
  local profile_json="$1"
  local log_source="$2"
  [[ -z "$profile_json" ]] && die "egress_propose_allowlist_diff: missing profile JSON"
  [[ -r "$log_source" ]] || { log_warn "egress: no log source at $log_source — nothing to propose"; return 0; }

  # Already-allowed hostnames (lowercased for comparison).
  local already
  already="$(jq -r '(.egress.allow // [])[] | ascii_downcase' <<<"$profile_json" | sort -u)"

  # Extract (dst_ip, dst_port) tuples from kernel LOG lines. iptables LOG
  # format includes "DST=<ip> ... DPT=<port>" (DST may be IPv4 or IPv6).
  local tuples
  tuples="$(grep -F '[boring-egress-attempt]' "$log_source" 2>/dev/null \
    | sed -nE 's/.*DST=([0-9a-fA-F:.]+).*DPT=([0-9]+).*/\1 \2/p' \
    | sort -u)"

  if [[ -z "$tuples" ]]; then
    echo "# No egress attempts were logged. Either the session made no outbound" >&2
    echo "# requests, or --learn-mode rules were not active." >&2
    return 0
  fi

  # Reverse-resolve each IP. Best-effort: IPs that don't reverse stay as IPs.
  local proposed=()
  local seen_hosts=""
  while IFS=' ' read -r ip port; do
    [[ -z "$ip" ]] && continue
    local host
    host="$(getent hosts "$ip" 2>/dev/null | awk '{print $2}' | head -1)"
    [[ -z "$host" ]] && host="$ip"
    host="$(echo "$host" | tr '[:upper:]' '[:lower:]')"

    # Skip if already in allowlist.
    if grep -qxF "$host" <<<"$already"; then continue; fi
    # Dedupe across this run.
    if grep -qxF "$host" <<<"$seen_hosts"; then continue; fi
    seen_hosts+="$host"$'\n'
    proposed+=("$host  # port $port")
  done <<<"$tuples"

  if [[ "${#proposed[@]}" -eq 0 ]]; then
    echo "# All observed egress attempts were already in egress.allow. No diff to propose." >&2
    return 0
  fi

  echo "# Add to .boring/profile.yaml egress.allow:"
  echo "egress:"
  echo "  allow:"
  # Preserve existing entries first, then append.
  jq -r '(.egress.allow // [])[] | "    - " + .' <<<"$profile_json"
  for entry in "${proposed[@]}"; do
    echo "    - $entry"
  done
}
